Update F01-userProfile

diff --git a/functions.d/F01-userProfile b/functions.d/F01-userProfile
--- a/functions.d/F01-userProfile
+++ b/functions.d/F01-userProfile
@@ -111,7 +111,19 @@ function runLoginCommands()
 
             if [[ -n "$(command -v ${cmnd_binary})" ]]; then
                 "${cmd_binary}" "${cmnd_args}"
-                ret_code=${?}
+                ret_code=${?};
+
+                if [[ -z "${ret_code}" ]] || (( ret_code != 0 )); then
+                    (( error_count += 1 ));
+
+                    if [[ "${LOGGING_LOADED}" == "${_TRUE}" ]]; then
+                        writeLogEntry "FILE" "ERROR" "${$}" "${cname}" "${LINENO}" "${function_name}" "Failed to create directory ${entry_target}.";
+                    fi
+
+                    continue;
+                fi
+            else
+                ## cmnd not found
             fi
         done
 
