Update manageDotFiles

diff --git a/bin/manageDotFiles b/bin/manageDotFiles
--- a/bin/manageDotFiles
+++ b/bin/manageDotFiles
@@ -432,7 +432,7 @@ function main()
                             (( error_count += 1 ))
 
                             [[ "${LOGGING_LOADED}" == "${_TRUE}" ]] && writeLogEntry "ERROR" "${CNAME}" "${function_name}" "${LINENO}" "Failed to execute installFiles with install type of ${INSTALL_LOCATION_LOCAL} as user ${TARGET_USER}. Please review logs.";
-						else
+                        else
                             if [[ -n "${ENABLE_DEBUG}" ]] && [[ "${ENABLE_DEBUG}" == "${_TRUE}" ]] && [[ "${LOGGING_LOADED}" == "${_TRUE}" ]]; then
                                 writeLogEntry "DEBUG" "${CNAME}" "${function_name}" "${LINENO}" "File reload complete.";
                                 writeLogEntry "DEBUG" "${CNAME}" "${function_name}" "${LINENO}" "EXEC: tput reset && source ${RELOAD_DOTFILE}";
@@ -442,49 +442,49 @@ function main()
                         fi
                     fi
                 else
-					if [[ -n "${ENABLE_DEBUG}" ]] && [[ "${ENABLE_DEBUG}" == "${_TRUE}" ]] && [[ "${LOGGING_LOADED}" == "${_TRUE}" ]]; then
-						writeLogEntry "DEBUG" "${CNAME}" "${function_name}" "${LINENO}" "transfer_file_list -> ${transfer_file_list}";
-						writeLogEntry "DEBUG" "${CNAME}" "${function_name}" "${LINENO}" "EXEC: transferFiles ${TRANSFER_LOCATION_REMOTE} ${transfer_file_list} ${TARGET_HOST} ${SSH_PORT_NUMBER} ${TARGET_USER} ${FORCE_EXEC}";
-					fi
+                    if [[ -n "${ENABLE_DEBUG}" ]] && [[ "${ENABLE_DEBUG}" == "${_TRUE}" ]] && [[ "${LOGGING_LOADED}" == "${_TRUE}" ]]; then
+                        writeLogEntry "DEBUG" "${CNAME}" "${function_name}" "${LINENO}" "transfer_file_list -> ${transfer_file_list}";
+                        writeLogEntry "DEBUG" "${CNAME}" "${function_name}" "${LINENO}" "EXEC: transferFiles ${TRANSFER_LOCATION_REMOTE} ${transfer_file_list} ${TARGET_HOST} ${SSH_PORT_NUMBER} ${TARGET_USER} ${FORCE_EXEC}";
+                    fi
 
-					[[ -n "${CNAME}" ]] && unset -v CNAME;
-					[[ -n "${function_name}" ]] && unset -v function_name;
-					[[ -n "${ret_code}" ]] && unset -v ret_code;
+                    [[ -n "${CNAME}" ]] && unset -v CNAME;
+                    [[ -n "${function_name}" ]] && unset -v function_name;
+                    [[ -n "${ret_code}" ]] && unset -v ret_code;
 
-					transferFiles "${TRANSFER_LOCATION_REMOTE}" "${transfer_file_list}" "${TARGET_HOST}" "${SSH_PORT_NUMBER}" "${TARGET_USER}" "${FORCE_EXEC}";
-					ret_code="${?}";
+                    transferFiles "${TRANSFER_LOCATION_REMOTE}" "${transfer_file_list}" "${TARGET_HOST}" "${SSH_PORT_NUMBER}" "${TARGET_USER}" "${FORCE_EXEC}";
+                    ret_code="${?}";
 
-					CNAME="$(basename "${BASH_SOURCE[0]}")";
-					function_name="${CNAME}#${FUNCNAME[0]}";
+                    CNAME="$(basename "${BASH_SOURCE[0]}")";
+                    function_name="${CNAME}#${FUNCNAME[0]}";
 
-					if [[ -n "${ENABLE_DEBUG}" ]] && [[ "${ENABLE_DEBUG}" == "${_TRUE}" ]] && [[ "${LOGGING_LOADED}" == "${_TRUE}" ]]; then writeLogEntry "DEBUG" "${CNAME}" "${function_name}" "${LINENO}" "ret_code -> ${ret_code}"; fi
+                    if [[ -n "${ENABLE_DEBUG}" ]] && [[ "${ENABLE_DEBUG}" == "${_TRUE}" ]] && [[ "${LOGGING_LOADED}" == "${_TRUE}" ]]; then writeLogEntry "DEBUG" "${CNAME}" "${function_name}" "${LINENO}" "ret_code -> ${ret_code}"; fi
 
-					if [[ -z "${ret_code}" ]] || (( ret_code != 0 )); then
-						(( error_count += 1 ));
+                    if [[ -z "${ret_code}" ]] || (( ret_code != 0 )); then
+                        (( error_count += 1 ));
 
-						[[ "${LOGGING_LOADED}" == "${_TRUE}" ]] && writeLogEntry "ERROR" "${CNAME}" "${function_name}" "${LINENO}" "Failed to execute transferFiles with transfer type of ${TRANSFER_LOCATION_REMOTE}. Please review logs.";
-					else
-						if [[ -n "${ENABLE_DEBUG}" ]] && [[ "${ENABLE_DEBUG}" == "${_TRUE}" ]] && [[ "${LOGGING_LOADED}" == "${_TRUE}" ]]; then writeLogEntry "DEBUG" "${CNAME}" "${function_name}" "${LINENO}" "EXEC: reloadDotFiles"; fi
+                        [[ "${LOGGING_LOADED}" == "${_TRUE}" ]] && writeLogEntry "ERROR" "${CNAME}" "${function_name}" "${LINENO}" "Failed to execute transferFiles with transfer type of ${TRANSFER_LOCATION_REMOTE}. Please review logs.";
+                    else
+                        if [[ -n "${ENABLE_DEBUG}" ]] && [[ "${ENABLE_DEBUG}" == "${_TRUE}" ]] && [[ "${LOGGING_LOADED}" == "${_TRUE}" ]]; then writeLogEntry "DEBUG" "${CNAME}" "${function_name}" "${LINENO}" "EXEC: reloadDotFiles"; fi
 
-						[[ -n "${CNAME}" ]] && unset -v CNAME;
-						[[ -n "${function_name}" ]] && unset -v function_name;
-						[[ -n "${ret_code}" ]] && unset -v ret_code;
+                        [[ -n "${CNAME}" ]] && unset -v CNAME;
+                        [[ -n "${function_name}" ]] && unset -v function_name;
+                        [[ -n "${ret_code}" ]] && unset -v ret_code;
 
-						installFiles "${INSTALL_LOCATION_REMOTE}" "${TARGET_HOST}" "${SSH_PORT_NUMBER}" "${TARGET_USER}" "${FORCE_EXEC}";
-						ret_code="${?}";
+                        installFiles "${INSTALL_LOCATION_REMOTE}" "${TARGET_HOST}" "${SSH_PORT_NUMBER}" "${TARGET_USER}" "${FORCE_EXEC}";
+                        ret_code="${?}";
 
-						CNAME="$(basename "${BASH_SOURCE[0]}")";
-						function_name="${CNAME}#${FUNCNAME[0]}";
-					
-						if [[ -n "${ENABLE_DEBUG}" ]] && [[ "${ENABLE_DEBUG}" == "${_TRUE}" ]] && [[ "${LOGGING_LOADED}" == "${_TRUE}" ]]; then
-							writeLogEntry "DEBUG" "${CNAME}" "${function_name}" "${LINENO}" "ret_code -> ${ret_code}";
-						fi
+                        CNAME="$(basename "${BASH_SOURCE[0]}")";
+                        function_name="${CNAME}#${FUNCNAME[0]}";
+                    
+                        if [[ -n "${ENABLE_DEBUG}" ]] && [[ "${ENABLE_DEBUG}" == "${_TRUE}" ]] && [[ "${LOGGING_LOADED}" == "${_TRUE}" ]]; then
+                            writeLogEntry "DEBUG" "${CNAME}" "${function_name}" "${LINENO}" "ret_code -> ${ret_code}";
+                        fi
 
-						if [[ -z "${ret_code}" ]] || (( ret_code != 0 )); then
-							(( error_count += 1 ))
+                        if [[ -z "${ret_code}" ]] || (( ret_code != 0 )); then
+                            (( error_count += 1 ))
 
-							[[ "${LOGGING_LOADED}" == "${_TRUE}" ]] && writeLogEntry "ERROR" "${CNAME}" "${function_name}" "${LINENO}" "Failed to execute installFiles with install type of ${INSTALL_LOCATION_LOCAL}. Please review logs.";
-						else
+                            [[ "${LOGGING_LOADED}" == "${_TRUE}" ]] && writeLogEntry "ERROR" "${CNAME}" "${function_name}" "${LINENO}" "Failed to execute installFiles with install type of ${INSTALL_LOCATION_LOCAL}. Please review logs.";
+                        else
                             if [[ -n "${ENABLE_DEBUG}" ]] && [[ "${ENABLE_DEBUG}" == "${_TRUE}" ]] && [[ "${LOGGING_LOADED}" == "${_TRUE}" ]]; then
                                 writeLogEntry "DEBUG" "${CNAME}" "${function_name}" "${LINENO}" "File reload complete.";
                                 writeLogEntry "DEBUG" "${CNAME}" "${function_name}" "${LINENO}" "EXEC: tput reset && source ${RELOAD_DOTFILE}";
@@ -492,9 +492,68 @@ function main()
 
                             tput reset && source "${RELOAD_DOTFILE}";
                         fi
-					fi
+                    fi
                 fi
             fi
+            ;;
+        [Rr][Ee][Mm][Oo][Vv][Ee][Dd][Oo][Tt][Ff][Ii][Ll][Ee][Ss])
+                if [[ "${TARGET_HOST}" == "${HOSTNAME}" ]] || [[ "${TARGET_HOST}" == "localhost" ]]; then
+                    if [[ -n "${ENABLE_DEBUG}" ]] && [[ "${ENABLE_DEBUG}" == "${_TRUE}" ]] && [[ "${LOGGING_LOADED}" == "${_TRUE}" ]]; then writeLogEntry "DEBUG" "${CNAME}" "${function_name}" "${LINENO}" "EXEC: uninstallFiles ${UNINSTALL_LOCATION_LOCAL}"; fi
+
+                    [[ -n "${CNAME}" ]] && unset -v CNAME;
+                    [[ -n "${function_name}" ]] && unset -v function_name;
+                    [[ -n "${ret_code}" ]] && unset -v ret_code;
+
+                    uninstallFiles "${UNINSTALL_LOCATION_LOCAL}";
+                    ret_code="${?}";
+
+                    CNAME="$(basename "${BASH_SOURCE[0]}")";
+                    function_name="${CNAME}#${FUNCNAME[0]}";
+
+                    if [[ -n "${ENABLE_DEBUG}" ]] && [[ "${ENABLE_DEBUG}" == "${_TRUE}" ]] && [[ "${LOGGING_LOADED}" == "${_TRUE}" ]]; then writeLogEntry "DEBUG" "${CNAME}" "${function_name}" "${LINENO}" "ret_code -> ${ret_code}"; fi
+
+                    if [[ -z "${ret_code}" ]] || (( ret_code != 0 )); then
+                        (( error_count += 1 ))
+
+                        if [[ "${LOGGING_LOADED}" == "${_TRUE}" ]]; then
+						    writeLogEntry "ERROR" "${CNAME}" "${function_name}" "${LINENO}" "Failed to execute uninstallFiles with uninstall type of ${UNINSTALL_LOCATION_LOCAL}. Please review logs.";
+						    writeLogEntry "STDERR" "${CNAME}" "${function_name}" "${LINENO}" "Failed to execute uninstallFiles with uninstall type of ${UNINSTALL_LOCATION_LOCAL}. Please review logs.";
+						fi
+                    else
+                        if [[ "${LOGGING_LOADED}" == "${_TRUE}" ]]; then
+						    writeLogEntry "INFO" "${CNAME}" "${function_name}" "${LINENO}" "dotfiles uninstall complete on host ${TARGET_HOST} for user ${TARGET_USER}.";
+						    writeLogEntry "STDOUT" "${CNAME}" "${function_name}" "${LINENO}" "dotfiles uninstall complete on host ${TARGET_HOST} for user ${TARGET_USER}.";
+						fi
+                    fi
+                else
+                    if [[ -n "${ENABLE_DEBUG}" ]] && [[ "${ENABLE_DEBUG}" == "${_TRUE}" ]] && [[ "${LOGGING_LOADED}" == "${_TRUE}" ]]; then writeLogEntry "DEBUG" "${CNAME}" "${function_name}" "${LINENO}" "EXEC: uninstallFiles ${UNINSTALL_LOCATION_LOCAL}"; fi
+
+                    [[ -n "${CNAME}" ]] && unset -v CNAME;
+                    [[ -n "${function_name}" ]] && unset -v function_name;
+                    [[ -n "${ret_code}" ]] && unset -v ret_code;
+
+                    uninstallFiles "${UNINSTALL_LOCATION_REMOTE}" "${TARGET_HOST}" "${SSH_PORT_NUMBER}" "${TARGET_USER}" "${FORCE_EXEC}";
+                    ret_code="${?}";
+
+                    CNAME="$(basename "${BASH_SOURCE[0]}")";
+                    function_name="${CNAME}#${FUNCNAME[0]}";
+
+                    if [[ -n "${ENABLE_DEBUG}" ]] && [[ "${ENABLE_DEBUG}" == "${_TRUE}" ]] && [[ "${LOGGING_LOADED}" == "${_TRUE}" ]]; then writeLogEntry "DEBUG" "${CNAME}" "${function_name}" "${LINENO}" "ret_code -> ${ret_code}"; fi
+
+                    if [[ -z "${ret_code}" ]] || (( ret_code != 0 )); then
+                        (( error_count += 1 ))
+
+                        if [[ "${LOGGING_LOADED}" == "${_TRUE}" ]]; then
+						    writeLogEntry "ERROR" "${CNAME}" "${function_name}" "${LINENO}" "Failed to execute uninstallFiles with uninstall type of ${UNINSTALL_LOCATION_REMOTE} on host ${TARGET_HOST} as user ${TARGET_USER}. Please review logs.";
+						    writeLogEntry "STDERR" "${CNAME}" "${function_name}" "${LINENO}" "Failed to execute uninstallFiles with uninstall type of ${UNINSTALL_LOCATION_REMOTE} on host ${TARGET_HOST} as user ${TARGET_USER}. Please review logs.";
+						fi
+                    else
+                        if [[ "${LOGGING_LOADED}" == "${_TRUE}" ]]; then
+						    writeLogEntry "INFO" "${CNAME}" "${function_name}" "${LINENO}" "dotfiles uninstall complete on host ${TARGET_HOST} for user ${TARGET_USER}.";
+						    writeLogEntry "STDOUT" "${CNAME}" "${function_name}" "${LINENO}" "dotfiles uninstall complete on host ${TARGET_HOST} for user ${TARGET_USER}.";
+						fi
+                    fi
+                fi
             ;;
         *)
             (( error_count += 1 ));
@@ -594,13 +653,13 @@ while (( ${#} > 0 )); do
     if [[ -n "${ENABLE_DEBUG}" ]] && [[ "${ENABLE_DEBUG}" == "${_TRUE}" ]] && [[ "${LOGGING_LOADED}" == "${_TRUE}" ]]; then writeLogEntry "DEBUG" "${CNAME}" "${METHOD_NAME}" "${LINENO}" "ARGUMENT -> ${ARGUMENT}"; fi
 
     case "${ARGUMENT}" in
-	    *=*)
+        *=*)
             ARGUMENT_NAME="$(cut -d "=" -f 1 <<< "${ARGUMENT// }" | sed -e "s/--//g" -e "s/-//g")";
             ARGUMENT_VALUE="$(cut -d "=" -f 2 <<< "${ARGUMENT}")";
 
             shift 1;
             ;;
-	    *)
+        *)
             ARGUMENT_NAME="$(cut -d "-" -f 2 <<< "${ARGUMENT}")";
             ARGUMENT_VALUE="${2}";
 
